### ISSUE TITLE
Lab folders are empty

### ISSUE THREAD

**Issue by 1kevgriff** [DanWahlin/NodeJSEndToEndCourseCode#1]
The BEGIN/END in all the lab folders is empty.. and I'm pretty sure they should have content in them :)

**Comment by DanWahlin** [comment]
The labs are dynamically built actually. Run these commands from the root folder:
npm installnode copyFolders.js
Sorry...didn't realize that your last run of the class used the older version of the lab files that didn't use this build process. Since I didn't hear anything I assumed all was well. 

On Tue, Jan 26, 2016 at 2:54 PM -0800, "Kevin Griffin" notifications@github.com wrote:

The BEGIN/END in all the lab folders is empty.. and I'm pretty sure they should have content in them :)
